db_path: ./data/db.json
validation_raw_path: ./Val_leads_data.pkl
train_raw_path: ./Train_leads_data.pkl
live_data_path: ./Live_Data
counterfactuals_path: ./insurance_rf_counterfactuals.csv
validation_generated_values_collection: predictions_values_counterfactuals
live_prediction_values_collection: live_predictions
feature_attribution_aggregated_values_collection: feature_attribution_aggregated_values
train_feature_attribution_generated_values_collection: feature_attribution_values_train
train_feature_attribution_aggregated_values_collection: feature_attribution_values_train_aggregated
validation_feature_attribution_generated_values_collection: feature_attribution_values_validation
validation_feature_attribution_aggregated_values_collection: feature_attribution_values_validation_aggregated
performance_generated_values_collection: performance_values
prediction_model_path: ./leads_xgb.sav
problem_type: binary
target_label_column: converted
target_class_definitions: 
  - 'Not_Converted'
  - 'Converted'
target_classes :
  Not_Converted: 0
  Converted: 1
probability_threshold: 0.3
id_column:
shap_method:
pipeline_predictor:
pipeline_transformer:
model_type: Tree
performance_metric: F1 Score
explainer_dump_path: ./explain_pickle_path/diabetes_explainer.pkl
categorical_features_indexes:
  - 0
  - 1
  - 2
  - 3
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
feature_names:
  - 'Lead Origin'
  - 'Lead Source'
  - 'Do Not Email'
  - 'Do Not Call'
  - 'TotalVisits'
  - 'Total Time Spent on Website'
  - 'Page Views Per Visit'
  - 'Last Activity'
  - 'Specialization'
  - 'What is your current occupation'
  - 'Tags'
  - 'Lead Quality'
  - 'City'
  - 'Last Notable Activity'

protected_attributes:
  -
protected_attributes_mappings: # protected attribute definitions, if applicable
  -
protected_feature_combinations: # protected feature combination definitions, if applicable
  -
prefered_class: 1
fairness_score_collection: fairness_values
fairness_metric: Synthetic Flip Test