db_path: ./data/db.json
validation_raw_path: ./Val_Insurance_data.pkl
train_raw_path: ./Train_Insurance_data.pkl
live_data_path: ./Live_Data
counterfactuals_path: ./insurance_rf_counterfactuals.csv
validation_generated_values_collection: predictions_values_counterfactuals
live_prediction_values_collection: live_predictions
feature_attribution_aggregated_values_collection: feature_attribution_aggregated_values
train_feature_attribution_generated_values_collection: feature_attribution_values_train
train_feature_attribution_aggregated_values_collection: feature_attribution_values_train_aggregated
validation_feature_attribution_generated_values_collection: feature_attribution_values_validation
validation_feature_attribution_aggregated_values_collection: feature_attribution_values_validation_aggregated
performance_generated_values_collection: performance_values
prediction_model_path: ./insurance_mlp.sav
problem_type: binary
target_label_column: premium_type
target_class_definitions: 
  - 'Low'
  - 'High'
target_classes :
  Low: 0
  High: 1
probability_threshold: 0.5
id_column:
shap_method:
pipeline_predictor:
pipeline_transformer:
model_type: Tree
performance_metric: F1 Score
explainer_dump_path: ./explain_pickle_path/diabetes_explainer.pkl
categorical_features_indexes:
  - 1
  - 4
  - 5
feature_names:
  - 'age'
  - 'sex'
  - 'bmi'
  - 'children'
  - 'smoker'
  - 'region'
protected_attributes:
  - 'sex'
  - 'region'
protected_attributes_mappings: # protected attribute definitions, if applicable
  sex:
    male: 1.0
    female: 0.0
  region:
    southwest: 0.0
    southeast: 1.0
    northwest: 2.0
    northeast: 3.0
protected_feature_combinations: #Intersectional fairnes combinations
  sex: 'region'
prefered_class: 1
fairness_score_collection: fairness_values
fairness_metric: Synthetic Flip Test