db_path: ./data/db.json
validation_raw_path: ./Val_hosp_mor.pkl
train_raw_path: ./Train_hosp_mor.pkl
live_data_path: ./Live_Data
counterfactuals_path: ./hosp_lr_counterfactuals.csv
validation_generated_values_collection: predictions_values_counterfactuals
live_prediction_values_collection: live_predictions
feature_attribution_aggregated_values_collection: feature_attribution_aggregated_values
train_feature_attribution_generated_values_collection: feature_attribution_values_train
train_feature_attribution_aggregated_values_collection: feature_attribution_values_train_aggregated
validation_feature_attribution_generated_values_collection: feature_attribution_values_validation
validation_feature_attribution_aggregated_values_collection: feature_attribution_values_validation_aggregated
performance_generated_values_collection: performance_values
prediction_model_path: ./hosp_mor_lr.sav
problem_type: binary
target_label_column: label
target_class_definitions: 
  - 'Low_Risk'
  - 'High_Risk'
target_classes:
  Low_Risk: 0.0
  High_Risk: 1.0
probability_threshold: 0.5
id_column:
shap_method:
pipeline_predictor:
pipeline_transformer:
model_type: Linear
performance_metric: Recall
explainer_dump_path: ./explain_pickle_path/diabetes_explainer.pkl
categorical_features_indexes:
  - 1
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
feature_names:
  - 'age'
  - 'gendera'
  - 'BMI'
  - 'hypertensive'
  - 'atrialfibrillation'
  - 'CHD with no MI'
  - 'diabetes'
  - 'deficiencyanemias'
  - 'depression'
  - 'Hyperlipemia'
  - 'Renal failure'
  - 'COPD'
  - 'heart rate'
  - 'Systolic blood pressure'
  - 'Diastolic blood pressure'
  - 'Respiratory rate'
  - 'temperature'
  - 'SP O2'
  - 'Urine output'
  - 'hematocrit'
  - 'RBC'
  - 'MCH'
  - 'MCHC'
  - 'MCV'
  - 'RDW'
  - 'Leucocyte'
  - 'Platelets'
  - 'Neutrophils'
  - 'Basophils'
  - 'Lymphocyte'
  - 'PT'
  - 'INR'
  - 'NT-proBNP'
  - 'Creatine kinase'
  - 'Creatinine'
  - 'Urea nitrogen'
  - 'glucose'
  - 'Blood potassium'
  - 'Blood sodium'
  - 'Blood calcium'
  - 'Chloride'
  - 'Anion gap'
  - 'Magnesium ion'
  - 'PH'
  - 'Bicarbonate'
  - 'Lactic acid'
  - 'PCO2'
  - 'EF'

protected_attributes: 
  - 'gendera'
protected_attributes_mappings: # protected attribute definitions, if applicable
  gendera:
    male: 2.0
    female: 1.0
protected_feature_combinations: # protected feature combination definitions, if applicable
prefered_class: 1.0
fairness_score_collection: fairness_values
fairness_metric: Synthetic Flip Test